prototype/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.HomePage.as_view(), name = 'home'),
    path('users/',include("users.urls", namespace='users')),
    path('requests/', include("requests.urls", namespace='requests')),
    path('trips/', include("trips.urls", namespace = 'trips'))

    ]

requests/urls.py
from django.conf.urls import url
from . import views

app_name = 'requests'

urlpatterns = [
    url(r'create/$', views.ListRequests.as_view(), name = 'create_request')
]

trips/urls.py
from django.conf.urls import url
from . import views

app_name = 'trips'

urlpatterns = [
    url(r'create/$', views.CreateTrip.as_view(), name = 'create_trip'),
    url(r'confirm/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.TripConfirm.as_view(), name = 'confirm_trip')
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView
# from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
        url(r"signup/$", views.SignUp.as_view(), name='signup'),
        url(r"login/$", LoginView.as_view(template_name='users/login.html'), name='login'),
        url(r"logout/$", LogoutView.as_view(template_name='users/logout.html'), name='logout')
]

requests/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime
# Create your models here.
from django.contrib.auth import get_user_model
User = get_user_model()

class Requests(models.Model):
    DESTINATIONS = [
    ('BLVD', 'Boulevard ASIA'),
    ('PH', 'Punta Hermosa'),
    ('PARACAS', 'Paracas'),
    ('ELROS', 'El Rosario'),
    ('CERROA',  'Cerro Azul')
    ]
    user = models.ForeignKey(User, related_name="requests", on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now=True, null=False)
    date_request = models.DateTimeField(auto_now = False, default = datetime.now(), null = False, editable = True)
    destination = models.CharField(max_length=64, choices = DESTINATIONS)
    address = models.TextField(blank = True, default = '')

    def __str__(self):
        return self.address

    def get_absolute_url(self):
        return reverse('home')

trips/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from datetime import datetime
User = get_user_model()

class Trip(models.Model):
    DESTINATIONS = [
    ('BLVD', 'Boulevard ASIA'),
    ('PH', 'Punta Hermosa'),
    ('PARACAS', 'Paracas'),
    ('ELROS', 'El Rosario'),
    ('CERROA',  'Cerro Azul')
    ]
    SPACES = [
    (1,1), (2,2), (3,3), (4,4), (5,5)
    ]
    user = models.ForeignKey(User, related_name="trips", on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now=True, null=False)
    date_request = models.DateTimeField(auto_now = False, default = datetime.now(), null = False, editable = True)
    origin = models.CharField(max_length=100, null=False)
    places = models.SmallIntegerField(choices = SPACES, null=False)
    destination = models.CharField(max_length=64, choices = DESTINATIONS)
    description = models.TextField(blank = True, default = '')

    def __str__(self):
        return self.destination

    def get_absolute_url(self):
        return reverse('trips:confirm_trip', kwargs={
                                    'username': self.user.username,
                                    'pk': self.pk}
                                    )

# Create your models here.

users/models.py
from django.db import models

# Create your models here.
# class User(models.Model):
#     username = models.CharField(max_length=30)
#     first_name = models.CharField(max_length=30)
#     last_name = models.CharField(max_length=30)
#     email = models.EmailField(max_length=50)
#     password1 = models.CharField(max_length=50)
#     password2 = models.CharField(max_length=50)

requests/forms.py
from django import forms

from . import models

class RequestsForm(forms.ModelForm):
    class Meta:
        model = models.Requests
        fields = ['destination', 'address', 'date_request']
        widgets = {
            'date': forms.DateTimeInput()
        }

trips/forms.py
from django import forms

from . import models

class TripForm(forms.ModelForm):
    class Meta:
        model = models.Trip
        fields = ['origin', 'destination', 'places','description','date_request']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

prototype/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.

class HomePage(TemplateView):
    template_name = 'base.html'

requests/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from braces.views import SelectRelatedMixin
from django.urls import reverse_lazy
from . import forms
from . import filters
from trips.models import Trip


from . import forms
from . import models

# Create your views here.
class CreateRequest(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    # fields = ('destination', 'address', 'date')
    form_class = forms.RequestsForm
    model = models.Requests

    def form_valid(self, form):
        self.object = form.save(commit = False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class ListRequests(generic.ListView):
    model = Trip
    template_name = 'requests/select_request.html'
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = filters.TripFilter(self.request.GET, queryset = self.get_queryset())
        return context

trips/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from braces.views import SelectRelatedMixin
from django.urls import reverse_lazy
from . import forms


from . import forms
from . import models

# Create your views here.
class CreateTrip(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    # fields = ('destination', 'address', 'date')
    form_class = forms.TripForm
    model = models.Trip

    def form_valid(self, form):
        self.object = form.save(commit = False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class TripConfirm(LoginRequiredMixin, SelectRelatedMixin, generic.DetailView):
    model = models.Trip
    select_related = ('user',)

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )

users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView
from . import forms

# Create your views here.

class SignUp(CreateView):
    form_class = forms.SignUpForm
    template_name = 'users/signup.html'
    success_url = reverse_lazy("login")

class LogoutPage(TemplateView):
    template_name = 'logout.html'
    success_url = reverse_lazy("logout")

requests/templates/requests/requests_form.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block content %}
<h4>Create New Request</h4>

<form method="POST" action="{% url 'requests:create_request' %}" id="postForm">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" value="Request" class="btn btn-primary btn-large">
</form>
<script>
        $('#id_date_request').datetimepicker({ footer: true, modal: true, format: 'yyyy-mm-dd HH:MM'});
</script>

{% endblock %}

requests/templates/requests/select_request.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block content %}
<h4>¿A dónde vas?</h4>

<form method="GET">
  {% bootstrap_form filter.form %}
  <button type="submit" class="btn btn-primary">Buscar Viajes</button>
</form>

<table>
  {% for trip in filter.qs %}
    <tr>
      <td>Usuario:{{trip.user}}</td>
      <td>Destino:{{ trip.destination }}</td>
      <td>Salida:{{trip.date_request}}</td>
      <td>Lugares disponibles:{{trip.places}}</td>
      <td><a href="{%url 'trips:confirm_trip' trip.user trip.pk %}" class="btn btn-primary" role = "button">Solicitar</a></td>
    </tr>

  {% endfor %}
</table>


{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Prototype</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="{% static 'prototype/js/gijgo.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.min.css' %}">
    {% block html_head %} {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" role="navigation" id="navbar">
    			<div class="container">

            <a class="navbar-brand mynav" href="{% url 'home' %}">Prototype</a>

    					<ul class="nav navbar-nav navbar-right" id="navlinks">
                {% if user.is_authenticated %}
                <li class="nav-item active"><a href="{% url "requests:create_request" %}" class="btn btn-simple text-white">Create Request</a></li>
                <li class="nav-item active"><a href="{% url "trips:create_trip" %}" class="btn btn-simple text-white">Create Ride</a></li>
                <li class="nav-item active"><a href=# class="btn btn-simple text-white">My Requests</a></li>
                <li class="nav-item active"><a href="{% url "users:logout" %}" class="btn btn-simple text-white">Logout</a></li>

                {% else %}
    						<li class="nav-item active"><a href="{% url "users:login" %}" class="btn btn-simple text-white">Login</a></li>
                <li class="nav-item active"><a href="{% url "users:signup" %}" class="btn btn-simple text-white">Signup</a></li>
                {% endif %}
    					</ul>

    			</div>
    		</nav>
        <div class="container" id="titletop">
          <h1>Welcome to Prototype!</h1>
          <p>Create a user and log in</p>
        </div>
        {% block content %}
        {% endblock %}

  </body>
</html>

templates/logout.html
{% extends "base.html" %}

{% block content %}

<h1>THANKS FOR USING PROTOTYPE!</h1>
<p>Login again if you still want to use the app</p>

{% endblock %}

trips/templates/trips/trip_detail.html
{% extends 'base.html' %}



{% block content %}


  <div class="container" id="tripconftitle" style="text-align:center">
    <h2>Confirma los datos de tu viaje</h2>
    <h3>Debajo están los detalles:</h3>
    <p>Nombre de usuario: {{user.username}}</p>
    <p>Punto de salida: {{trip.origin}}</p>
    <p>Punto de llegada: {{trip.destination}}</p>
    <p>Fecha y hora de salida: {{trip.date_request}}</p>
    <p>Lugares disponibles: {{trip.places}}</p>
  </div>


{% endblock %}

trips/templates/trips/trip_form.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block content %}
<h4>Create New Ride</h4>

<form method="POST" action="{% url 'trips:create_trip' %}" id="tripForm">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" value="Request" class="btn btn-primary btn-large">
</form>
<script>
        $('#id_date_request').datetimepicker({ footer: true, modal: true, format: 'yyyy-mm-dd HH:MM'});
</script>

{% endblock %}

users/templates/users/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1>Enter your credentials</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-default">
    </form>
</div>
{% endblock %}

users/templates/users/logout.html
{% extends "base.html" %}

{% block content %}
<h1>THANKS FOR USING PROTOTYPE!</h1>
<p>Come back soon or login again</p>
{% endblock %}

users/templates/users/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Sign Up" class="btn btn-default">
    </form>
</div>
{% endblock %}